# Generated by Django 5.2.8 on 2025-12-02 11:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoshqarmaTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/boshqarma_haqida/', verbose_name='Asosiy Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Boshqarma Haqida',
                'verbose_name_plural': 'Boshqarma Haqida',
            },
        ),
        migrations.CreateModel(
            name='ElonVaTadbirlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='Images/elon_va_tadbirlar/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Elon va Tadbir',
                'verbose_name_plural': 'Elon va Tadbirlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ErishilganYutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='yutuqlar/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Erishilgan Yutuq',
                'verbose_name_plural': 'Erishilgan Yutuqlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MatbuotXizmati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=455, null=True, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='Images/matbuot/', verbose_name='Asosiy Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('content_uz', models.TextField(null=True, verbose_name='Kontent')),
                ('content_en', models.TextField(null=True, verbose_name='Kontent')),
                ('content_ru', models.TextField(null=True, verbose_name='Kontent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Qoyilgan Sana')),
                ('murojat_kimga', models.CharField(choices=[('rahbar', 'Rahbar'), ('urinbosar', 'O‘rinbosar')], default='rahbar', max_length=20)),
                ('murojat_turi', models.CharField(choices=[('shikoyat', 'Shikoyat'), ('taklif', 'Taklif'), ('savol', 'Savol')], default='savol', max_length=20)),
                ('familiya', models.CharField(max_length=255)),
                ('ismi', models.CharField(max_length=255)),
                ('otasining_ismi', models.CharField(blank=True, max_length=255, null=True)),
                ('kompaniyaning_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('boglanish_malumotlari', models.CharField(max_length=255)),
                ('pochta_manzil', models.EmailField(max_length=254)),
                ('mirojat_matni', models.TextField()),
                ('hujjatlar', models.FileField(blank=True, null=True, upload_to='murojatlar/')),
                ('tel_raqam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QabulJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Politexnikum nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi')),
                ('matn', ckeditor.fields.RichTextField()),
                ('matn_uz', ckeditor.fields.RichTextField(null=True)),
                ('matn_en', ckeditor.fields.RichTextField(null=True)),
                ('matn_ru', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to='Images/qabul_jadvali/', verbose_name='Asosiy Rasm')),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': 'Qabul Jadvali',
                'verbose_name_plural': 'Qabul Jadvali',
            },
        ),
        migrations.CreateModel(
            name='BoShIshOrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/bo_shish_orin/', verbose_name='Rasm')),
                ('lavozim', models.CharField(max_length=100)),
                ('lavozim_uz', models.CharField(max_length=100, null=True)),
                ('lavozim_en', models.CharField(max_length=100, null=True)),
                ('lavozim_ru', models.CharField(max_length=100, null=True)),
                ('joylashuv', models.CharField(max_length=100)),
                ('joylashuv_uz', models.CharField(max_length=100, null=True)),
                ('joylashuv_en', models.CharField(max_length=100, null=True)),
                ('joylashuv_ru', models.CharField(max_length=100, null=True)),
                ('sana', models.DateField()),
                ('tavsif', models.TextField()),
                ('tavsif_uz', models.TextField(null=True)),
                ('tavsif_en', models.TextField(null=True)),
                ('tavsif_ru', models.TextField(null=True)),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('boshqarma_tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoShIshOrin', to='news_app.boshqarmatarixi', verbose_name='Tegishli boshqarma tarix')),
            ],
        ),
        migrations.CreateModel(
            name='ElonVaTadbirlarRasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/elon_va_tadbirlar/', verbose_name='Elon va Tadbir Rasmi')),
                ('elon_tadbir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.elonvatadbirlar', verbose_name='Tegishli Elon yoki Tadbir')),
            ],
            options={
                'verbose_name': 'Elon va Tadbir Rasmi',
                'verbose_name_plural': 'Elon va Tadbir Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='ErishilganYutuqRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yutuqlar/', verbose_name='Yutuq Rasmi')),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.erishilganyutuqlar', verbose_name='Tegishli Yutuq')),
            ],
            options={
                'verbose_name': 'Yutuq Rasmi',
                'verbose_name_plural': 'Yutuq Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='MatbuotXizmatiRasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='matbuot/', verbose_name='Matbuot Rasmi')),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='news_app.matbuotxizmati', verbose_name='Tegishli Matbuot')),
            ],
            options={
                'verbose_name': 'Yangiliklar Rasmi',
                'verbose_name_plural': 'Yangiliklar Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='MurojatHammuallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=255)),
                ('ismi', models.CharField(max_length=255)),
                ('otasining_ismi', models.CharField(blank=True, max_length=255, null=True)),
                ('pochta_manzil', models.EmailField(max_length=254)),
                ('murojat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murojat_hammuallif', to='news_app.murojat', verbose_name='Tegishli Murojat')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('ism_uz', models.CharField(max_length=100, null=True)),
                ('ism_en', models.CharField(max_length=100, null=True)),
                ('ism_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='Images/rahbariyat/', verbose_name='Rasm')),
                ('lavozim', models.CharField(max_length=100)),
                ('lavozim_uz', models.CharField(max_length=100, null=True)),
                ('lavozim_en', models.CharField(max_length=100, null=True)),
                ('lavozim_ru', models.CharField(max_length=100, null=True)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('view_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('boshqarma_tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rahbariyatlar', to='news_app.boshqarmatarixi', verbose_name='Tegishli Rahbariyat')),
            ],
        ),
    ]
