# Generated by Django 5.2.8 on 2025-12-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_homeslider_homeimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriyaSilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Galereya Rasmi',
                'verbose_name_plural': 'Galereya Rasmlari',
            },
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Bosh sahifa raslari ', 'verbose_name_plural': 'Bosh sahifa rasmlari'},
        ),
        migrations.CreateModel(
            name='GaleriyaRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galereya/', verbose_name='Galereya Rasmi')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_app.galeriyasilder')),
            ],
        ),
    ]
